name: 'nba_goat_analytics'
version: '1.0.0'
config-version: 2

profile: 'nba_goat'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nba_goat_analytics:
    # Staging models - raw data cleaned
    staging:
      +materialized: view
      +schema: staging
      
    # Intermediate models - business logic
    intermediate:
      +materialized: view
      +schema: intermediate
      
    # Marts - final analytics tables
    marts:
      +materialized: table
      +schema: marts
      
    # Metrics - business metrics definitions
    metrics:
      +materialized: view
      +schema: metrics

seeds:
  +quote_columns: false

tests:
  +store_failures: true
  +schema: test_results
